version: "3.9"

services:
  sftp:
    image: atmoz/sftp:debian
    container_name: sftp
    ports:
      - "${HOST_SSH_PORT}:22"
    restart: unless-stopped
    cap_add:
      - SYS_ADMIN
    volumes:
      - ./ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./users.conf:/etc/sftp/users.conf:ro
      - ./bindmount.sh:/etc/sftp.d/bindmount.sh
      - /data/sftp-data:/data

networks:
  default:
    name: nginx-proxy
    external: true
