version: "3.9"

services:
  sftp:
    image: atmoz/sftp:debian
    container_name: sftp
    ports:
      - "${HOST_SSH_PORT}:22"
    restart: unless-stopped
    # Bind mount require privilege. `--cap_add=SYS_ADMIN` doesn't work.
    # See: https://github.com/atmoz/sftp/issues/60#issuecomment-332909232
    # cap_add:
    #   - SYS_ADMIN
    # We use more privileges to do this:
    privileged: True
    volumes:
      - ./ssh_host_ed25519_key:/etc/ssh/ssh_host_ed25519_key:ro
      - ./ssh_host_rsa_key:/etc/ssh/ssh_host_rsa_key:ro
      - ./users.conf:/etc/sftp/users.conf:ro
      - ./bindmount.sh:/etc/sftp.d/bindmount.sh
      - /data/sftp-data:/data

networks:
  default:
    name: nginx-proxy
    external: true
