version: "3.9"

x-logging:
  &default-logging
  driver: "json-file"
  options:
    max-size: 4m
    max-file: 10

x-depends_on:
  &default-depends_on
  cms-cbna-test-mariadb:
    condition: service_healthy

services:
  cms-cbna-test-nginx:
    image: nginx:1.24.0-bullseye
    # https://hub.docker.com/_/nginx
    container_name: cms-cbna-test-nginx
    hostname: "${HOSTNAME}_cms-cbna-test-nginx"
    restart: unless-stopped
    depends_on:
      << : *default-depends_on
      cms-cbna-test-wordpress:
        condition: service_healthy
    expose:
      - 80
    environment:
      TZ: ${TZ:-Europe/Paris}
      VIRTUAL_HOST: "${SITE_DOMAIN_ALL}"
      LETSENCRYPT_HOST: "${SITE_DOMAIN_ALL}"
    healthcheck:
      test: ["CMD-SHELL", "curl --fail http://localhost:9090/nginx_status || exit 1"]
      interval: 1m30s
      timeout: 10s
      retries: 3
    logging: *default-logging
    volumes:
      - ./nginx/.htpasswd:/etc/nginx/.htpasswd
      - ./nginx/conf.d/cbn-alpin.conf:/etc/nginx/templates/default.conf.template
      - ./nginx/conf.d/status.conf:/etc/nginx/conf.d/status.conf:ro
      - wordpress-cbna-cms-storage:/var/www/html

  cms-cbna-test-wordpress:
    build:
      context: ./wordpress/build
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-Europe/Paris}
        WP_BACKUP_DATE: ${WP_BACKUP_DATE-"None"}
    image: cbna/cms-test-wordpress:wordpress-6.3.1-php8.2-fpm
    # https://hub.docker.com/_/wordpress
    container_name: cms-cbna-test-wordpress
    hostname: "${HOSTNAME}_cms-cbna-test-wordpress"
    restart: unless-stopped
    depends_on: *default-depends_on
    expose:
      - 9000
    environment:
      TZ: ${TZ:-Europe/Paris}
      WORDPRESS_DB_HOST: cms-cbna-test-mariadb:3306
      WORDPRESS_DB_NAME: ${MARIADB_DB}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
      # WORDPRESS_DEBUG : use an empty string to disable
      WORDPRESS_DEBUG: ""
      # WORDPRESS_CONFIG_EXTRA: |
        # //define('FORCE_SSL_ADMIN', true);
        # define('WPMS_ON', true);
        # define('WPMS_SMTP_PASS', '${WPMS_SMTP_PASS}');
    healthcheck:
      test: ["CMD-SHELL", "php-fpm-healthcheck"]
      interval: 10s
      timeout: 3s
      retries: 3
    volumes:
      - wordpress-cbna-cms-storage:/var/www/html

  cms-cbna-test-wp-cli:
    # Usage:
    # - change site URL in database:
    #   `docker compose run --rm cms-cbna-wp-cli wp search-replace wp.cbn-alpin.fr test-wp.cbn-alpin.fr --all-tables`
    # - change site Scheme (http => https) :
    #   `docker compose run --rm cms-cbna-wp-cli wp option update home 'https://test-wp.cbn-alpin.fr'`
    #   `docker compose run --rm cms-cbna-wp-cli wp option update siteurl 'https://test-wp.cbn-alpin.fr'`
    image : wordpress:cli-2.8.1-php8.2
    # https://hub.docker.com/_/wordpress
    container_name: cms-cbna-test-wp-cli
    hostname: "${HOSTNAME}_cms-cbna-test-wp-cli"
    restart: "no"
    profiles: ["cli"]
    environment:
      TZ: ${TZ:-Europe/Paris}
      WORDPRESS_DB_HOST: cms-cbna-test-mariadb:3306
      WORDPRESS_DB_NAME: ${MARIADB_DB}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
    depends_on:
      << : *default-depends_on
      cms-cbna-test-wordpress:
        condition: service_healthy
    volumes:
      - wordpress-cbna-cms-storage:/var/www/html

  cms-cbna-test-mariadb:
    image: mariadb:11.1.2-jammy
    # https://hub.docker.com/_/mariadb
    container_name: cms-cbna-test-mariadb
    hostname: "${HOSTNAME}_cms-cbna-test-mariadb"
    restart: unless-stopped
    expose:
      - 3306
    environment:
      TZ: ${TZ:-Europe/Paris}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      MARIADB_DATABASE: ${MARIADB_DB}
      MARIADB_USER: ${MARIADB_USER}
      MARIADB_PASSWORD: ${MARIADB_PASSWORD}
      # See : https://github.com/docker-library/mariadb/issues/160
      MARIADB_INITDB_SKIP_TZINFO: "yes"
    healthcheck:
      test: ["CMD-SHELL", "healthcheck.sh --connect --innodb_initialized"]
      interval: 10s
      timeout: 5s
      retries: 3
    logging: *default-logging
    volumes:
      - db-cbna-cms-storage:/var/lib/mysql
      - ./mariadb/initdb.d/:/docker-entrypoint-initdb.d/

  cms-cbna-test-adminer:
    image: adminer:4.8.1-standalone
    # https://hub.docker.com/_/adminer
    container_name: cms-cbna-test-adminer
    hostname: "${HOSTNAME}_cms-cbna-test-adminer"
    restart: unless-stopped
    expose:
      - 8080
    depends_on: *default-depends_on
    environment:
      TZ: ${TZ:-Europe/Paris}
      VIRTUAL_HOST: "${ADMINER_DOMAIN}"
      LETSENCRYPT_HOST: "${ADMINER_DOMAIN}"
      ADMINER_DESIGN: lucas-sandery
      ADMINER_DEFAULT_SERVER: cms-cbna-test-mariadb

  cms-cbna-test-backup-cron:
    build:
      context: ./cron/build
      dockerfile: Dockerfile
      args:
        TZ: ${TZ:-Europe/Paris}
        MARIADB_REPO_SETUP_CHECKSUM: ${MARIADB_REPO_SETUP_CHECKSUM}
        HOST_USER_NAME: ${HOST_USER_NAME}
        HOST_USER_ID: ${HOST_USER_ID}
        HOST_GROUP_ID: ${HOST_GROUP_ID}
    image: cbna/cms-test-backup-cron:debian-12.1-slim
    container_name: cms-cbna-test-backup-cron
    hostname: "${HOSTNAME}_cms-cbna-test-backup-cron"
    restart: unless-stopped
    depends_on: *default-depends_on
    environment:
      TZ: ${TZ:-Europe/Paris}
      MARIADB_ROOT_PASSWORD: ${MARIADB_ROOT_PASSWORD}
      WORDPRESS_DB_HOST: cms-cbna-test-mariadb:3306
      WORDPRESS_DB_NAME: ${MARIADB_DB}
      WORDPRESS_DB_USER: ${MARIADB_USER}
      WORDPRESS_DB_PASSWORD: ${MARIADB_PASSWORD}
      WORDPRESS_TABLE_PREFIX: ${WP_TABLE_PREFIX}
    logging: *default-logging
    volumes:
        - wordpress-cbna-cms-storage:/var/www/html
        - ./backups:/backups

volumes:
  db-cbna-cms-storage:
  wordpress-cbna-cms-storage:

networks:
  default:
    name: nginx-proxy
    external: true
